services:
  - type: web
    name: email_auth
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn email_auth.wsgi"
    deployCommand: "python manage.py migrate"
